from __future__ import annotations

from typing import Any

try:
    from generated.KunsamuLangVisitor import KunsamuLangVisitor
except ImportError:
    class KunsamuLangVisitor:  # type: ignore[no-redef]
        """Fallback used before running scripts/generate_antlr.ps1."""

        pass


class KunsamuANTLRVisitor(KunsamuLangVisitor):
    """Integration point for the Visitor generated by ANTLR4.

    The current web demo uses the project parser to remain executable in
    environments where ANTLR artifacts have not been generated yet. Once
    `scripts/generate_antlr.ps1` is executed, this class can be extended with
    generated context methods such as `visitComunidad`, `visitTerritorio` and
    `visitCurso`.
    """

    def visitProgram(self, ctx: Any) -> Any:
        return self.visitChildren(ctx)
